import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./components/header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ko">
      <body>
        <div className="main_container">
          <div className="main_nav">
          </div>
          <div className="main_header">
            <Header />
          </div>
          <div className="main_footer"></div>
          <div className="main_content">{children}</div>
          <div className="main_logo"></div>
        </div>
      </body>
    </html>
  );
}
